{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f524f9d6-6906-44ad-b3c6-d3620eb28d0d",
   "metadata": {},
   "outputs": [],
   "source": [
    "#MAY STILL NEED TO ADD READING_FUNC_ARGS TO SALSA.GENERATE_CATALOG\n",
    "\n",
    "import yt\n",
    "import salsa\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import matplotlib as plt\n",
    "\n",
    "#print(\"let's do some math, kids\", flush=True)\n",
    "\n",
    "def sal(ds_file='/mnt/research//galaxies-REU/sims/FOGGIE/halo_002392/nref11c_nref9f/RD0020', ray_dir='rays', n_rays=4, ray_num=0, center_list=[0.53, 0.53, 0.53], ion_list = ['H I', 'C IV', 'O VI'], df_type = 'cat', **kwargs):\n",
    "    \"\"\"\n",
    "    Does all the dirty work. \n",
    "    Uses yt to load nifty halo dataset. Uses a list of cool ions and SALSA to generate trident LightRay objects and extract absorbers from them. Returns a pandas dataset that contains info on absorbers from singular ray file, many ray files, or a catalog of all ray files with all absorbers. Catalog is the default. \n",
    "\n",
    "    :ds_file: Dataset with halo information. Uses HireIsolatedGalaxy by default\n",
    "\n",
    "    :ray_dir: Directory path where ray.h5 files with be stored\n",
    "\n",
    "    :n_rays: Number of trident LightRay objects to create. Default is 4\n",
    "\n",
    "    :ray_num: Used for indexing and saving ray.h5 files so they are not continuously overridden. Default is 0, so saved and/or indexed file will read \"ray0.h5\"\n",
    "\n",
    "    :center_list: Defined center of galaxy (I think...). Default is x,y,z = 0.53\n",
    "\n",
    "    :ion_list: Ions to add to generated spectrum\n",
    "\n",
    "    :df_type: Preferred data to be returned -- info on absorbers from a single ray file, many ray files, or a catalog of all ray files with all absorbers. Catalog is the default.\n",
    "\n",
    "    :kwargs: Contains necessary information for returning information oabsorbers frm many ray files (specify as a dictionary named \"mult\" in kwargs, great place to add an abundance table to be \t\t passed to salsa.AbsorberExtractor(), etc.\n",
    "    \"\"\"\n",
    "    print(f\"DATAFRAME TYPE: {df_type}\")\n",
    "    print(f'KWARGS: {kwargs}')\n",
    "\n",
    "    if 'mult' in kwargs:\n",
    "        mult = kwargs['mult']\n",
    "    else:\n",
    "        print('mult_args not given')\n",
    "        mult = {}\n",
    "\n",
    "    if 'reading_func_args' in kwargs:\n",
    "        funky_args = kwargs['reading_func_args']\n",
    "        mult['reading_func_args'] = funky_args\n",
    "    else:\n",
    "        print('reading_func_args not given')\n",
    "        funky_args = {}\n",
    "\n",
    "    #if ion_list == None:\n",
    "        #ion_list = ['H I', 'C IV', 'O VI']\n",
    "    if 'ion_list' in kwargs:\n",
    "        print(kwargs['ion_list'])\n",
    "    else:\n",
    "        print(\"ION LIST DIDN'T MAKE IT TO SAL THE SNAKE\")\n",
    "        print(f\"ION LIST: {ion_list}\") \n",
    "\n",
    "    def mult_salsa(ds, ray_directory, ray_file, units_dict, field, n_rays, ion_list, **mult):\n",
    "\n",
    "        if 'reading_func_args' in mult:\n",
    "            funky_args = mult['reading_func_args']\n",
    "\n",
    "        ray_list=[]\n",
    "        for i in range(n_rays):\n",
    "            if len(str(i)) == 1:\n",
    "                ray_list.append(f'{ray_directory}/ray00{i}.h5')\n",
    "            elif len(str(i)) == 2: \n",
    "                ray_list.append(f'{ray_directory}/ray0{i}.h5')\n",
    "            else:\n",
    "                ray_list.append(f'{ray_directory}/ray{i}.h5')\n",
    "\n",
    "        print(f\"RAY LIST: {ray_list}\")\n",
    "\n",
    "        return_df = pd.DataFrame()\n",
    "\n",
    "        for i in ion_list:\n",
    "            abs_ext_civ = salsa.AbsorberExtractor(ds, ray_file, ion_name = i, abundance_table_args = funky_args)\n",
    "            df_civ = salsa.get_absorbers(abs_ext_civ, ray_list, method='spice', fields=other_fields, units_dict=units_dict)\n",
    "            return_df = return_df.append(df_civ)\n",
    "\n",
    "        return return_df\n",
    "\n",
    "    #look for handy args in kwargs\n",
    "\n",
    "    #preliminary shenanigans -- load halo data; define handy variables; plant the seed, as it were\n",
    "    ds = yt.load(ds_file)\n",
    "\n",
    "    other_fields=['density', 'temperature', 'metallicity']\n",
    "    max_impact=15 #kpc\n",
    "    units_dict = dict(density='g/cm**3', metallicity='Zsun')\n",
    "\n",
    "    np.random.seed(69)\n",
    "\n",
    "    #get those rays babyyyy\n",
    "    print(f'ION LIST RIGHT BEFORE GENERATE_LRAYS: {ion_list}')\n",
    "    salsa.generate_lrays(ds, center_list, n_rays, max_impact, ion_list=ion_list, fields=other_fields, out_dir=ray_dir)\n",
    "\n",
    "    #get absorbers -- either many, singular, or catalog returned\n",
    "    if df_type == 'multiple':\n",
    "\n",
    "        if len(str(ray_num)) == 1:\n",
    "            new_ray_num = f'00{ray_num}'\n",
    "        elif len(str(ray_num)) == 2:\n",
    "            new_ray_num = f'0{ray_num}'\n",
    "        else:\n",
    "            new_ray_num=ray_num\n",
    "\n",
    "        ray_file=f'{ray_dir}/ray{new_ray_num}.h5'\n",
    "        spicy = mult_salsa(ds=ds, ray_directory=ray_dir, ray_file=ray_file, units_dict=units_dict, field=other_fields, n_rays=n_rays, ion_list=ion_list, **mult)\n",
    "\n",
    "        return spicy\n",
    "    if df_type == 'single': \n",
    "        ray_file=f'{ray_dir}/ray{ray_num}.h5'\n",
    "        abs_ext=salsa.AbsorberExtractor(ds, ray_file, ion_name='H I', **reading_func_args)\n",
    "        spicy = abs_ext.get_spice_absorbers(other_fields, units_dict=units_dict)\n",
    "\n",
    "        return spicy\n",
    "    if df_type == 'cat':\n",
    "        catalog = salsa.generate_catalog(ds, n_rays, ray_dir, ion_list, fields=other_fields, center = center_list, impact_param_lims=(0, max_impact), method='spice', units_dict=units_dict, reading_func_args = funky_args)\n",
    "\n",
    "        return catalog"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
